### ISSUE TITLE
Petite erreur que je ne comprends pas cctx key 

### ISSUE THREAD

**Issue by Roman01011** [CryptoRobotFr/Live-Tools-V2#1]
Hello, 

Je reçois l'erreur suivante lors de l'execution. Avez vous une idée pour le résoudre?

Merci d'avance!

-- Execution started at 2024-01-25 07:43:49 ---
Pair REN/USDT not found, removing from params...
Setting crossed x2 on 21 pairs...
Getting data and indicators on 21 pairs...
Traceback (most recent call last):
  File "/home/ubuntu/Live-Tools-V2/strategies/envelopes/multi_bitget.py", line 443, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/Live-Tools-V2/strategies/envelopes/multi_bitget.py", line 439, in main
    raise e
  File "/home/ubuntu/Live-Tools-V2/strategies/envelopes/multi_bitget.py", line 218, in main
    usdt_balance = await exchange.get_balance()
  File "/home/ubuntu/./Live-Tools-V2/utilities/bitget_perp.py", line 151, in get_balance
    resp = await self._session.fetch_balance()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/async_support/bitget.py", line 2003, in fetch_balance
    method = self.get_supported_mapping(marketType, {
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 1537, in get_supported_mapping
    raise NotSupported(self.id + ' ' + key + ' does not have a value in mapping')
ccxt.base.errors.NotSupported: bitget future does not have a value in mapping

**Comment by michelflight** [comment]
pip install ccxt==4.2.23 règlera ton problème
Si tu fais un pip show ccxt tu dois être dans une ancienne version, c'était aussi mon cas

**Comment by wikitab** [comment]
Hello,

J'ai une erreur lors de l'exécution :

Il y a eu une position prise sur MAGICUSDT mais sans stoploss.

--- Execution started at 2024-01-27 20:08:39 ---
Pair REN/USDT not found, removing from params...
Setting isolated x3 on 21 pairs...
Getting data and indicators on 21 pairs...
Balance: XXXXXXX USDT
Getting open trigger orders...
Canceling trigger orders...
Getting open orders...
Canceling limit orders...
Getting live positions...
Current position on MAGIC/USDT short - 162.8 ~ 184.71 $
Placing 2 close SL / limit order...
Traceback (most recent call last):
  File "/home/ubuntu/Live-Tools-V2/strategies/envelopes/multi_bitget.py", line 443, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/Live-Tools-V2/strategies/envelopes/multi_bitget.py", line 439, in main
    raise e
  File "/home/ubuntu/Live-Tools-V2/strategies/envelopes/multi_bitget.py", line 381, in main
    await asyncio.gather(*tasks_close)  # Limit orders when in positions
  File "/home/ubuntu/./Live-Tools-V2/utilities/bitget_perp.py", line 283, in place_order
    raise e
  File "/home/ubuntu/./Live-Tools-V2/utilities/bitget_perp.py", line 265, in place_order
    resp = await self._session.create_order(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/async_support/bitget.py", line 3918, in create_order
    response = await self.privateMixPostV2MixOrderPlaceOrder(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 759, in request
    return await self.fetch2(path, api, method, params, headers, body, config)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 756, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 243, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/async_support/bitget.py", line 7694, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: bitget {"code":"45117","msg":"Currently holding positions or orders, the margin mode cannot be adjusted","requestTime":1706386168418,"data":null}

Auriez-vous une idée ??
Merci les gars ;-)
