### ISSUE TITLE
stratégie enveloppe - erreur d'execution

### ISSUE THREAD

**Issue by P4sc4lS** [CryptoRobotFr/Live-Tools-V2#17]
Hello la team cryptorobot ;-)

Depuis quelques temps, l'execution de la strategie enveloppe sur bitget provoque des erreurs au moment de récupérer les positions live, dans la boucle for qui débute ligne 355 (multi_bitget.py)

La première position apparait bien, mais pas les suivantes, puis le code s'arrête et n'arrive jamais au bout.

Merci pour votre aide

      --- Execution started at 2024-12-13 16:55:53 ---
      Setting isolated x4 on 17 pairs...
      Getting data and indicators on 17 pairs...
      Balance: 789.38 USDT
      Getting open trigger orders...
      Canceling trigger orders...
      Getting open orders...
      Canceling limit orders...
      Getting live positions...
      Current position on JASMY/USDT short - 11075.0 ~ 511.61 $
      Traceback (most recent call last):
        File "/home/pascal/Live-Tools-V2/.venv/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
          return self._engine.get_loc(casted_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "index.pyx", line 153, in pandas._libs.index.IndexEngine.get_loc
        File "index.pyx", line 182, in pandas._libs.index.IndexEngine.get_loc
        File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
        File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
      KeyError: 'ma_low_-19'
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/home/pascal/Live-Tools-V2/strategies/envelopes/multi_bitget.py", line 574, in <module>
          asyncio.run(main())
        File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
          return runner.run(main)
                 ^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
          return self._loop.run_until_complete(task)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
          return future.result()
                 ^^^^^^^^^^^^^^^
        File "/home/pascal/Live-Tools-V2/strategies/envelopes/multi_bitget.py", line 570, in main
          raise e
        File "/home/pascal/Live-Tools-V2/strategies/envelopes/multi_bitget.py", line 442, in main
          position.pair, row[f"ma_low_{i+1}"]
                         ~~~^^^^^^^^^^^^^^^^^
        File "/home/pascal/Live-Tools-V2/.venv/lib/python3.11/site-packages/pandas/core/series.py", line 1111, in __getitem__
          return self._get_value(key)
                 ^^^^^^^^^^^^^^^^^^^^
        File "/home/pascal/Live-Tools-V2/.venv/lib/python3.11/site-packages/pandas/core/series.py", line 1227, in _get_value
          loc = self.index.get_loc(label)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/pascal/Live-Tools-V2/.venv/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3809, in get_loc
          raise KeyError(key) from err
      KeyError: 'ma_low_-19'
      sys:1: RuntimeWarning: coroutine 'PerpBitget.place_trigger_order' was never awaited
      sys:1: RuntimeWarning: coroutine 'PerpBitget.place_order' was never awaited

**Comment by michelflight** [comment]
curieux en effet, i+1 est égal à -19, tu as changé quelque chose dans le code ?

**Comment by P4sc4lS** [comment]
Non, à part l'ajout ou le retrait de quelques paires.
à l'entrée de la boucle, len(params[position.pair]["envelopes"]) vaut 4 (5 positions ouvertes). Jusque là ça parait normal, mais params[position.pair]["canceled_orders_buy"] vaut 24...bizarre

**Comment by michelflight** [comment]
c'est dans le traitement des paires non positionnées, len(params[position.pair]["envelopes"]) c'est le nombre de niveau sur lesquels les achats vont se faire en short et long (si tu as définis ces deux sens), tu pourrais printer la paire en question qui génère cette erreur ? et aussi partager la conf de cette paire ?

**Comment by P4sc4lS** [comment]
J'ai supprimé tous les ordres trigger, et toutes les paires sans positions. 
en relançant le code j'ai une erreur sur la paire LQTY/USDT:USDT :

  Placing 10 close SL / limit order...
  Error limit buy 246.5 LQTY/USDT:USDT - Price 2.40654 - Error => bitget {"code":"22047","msg":"The order price exceeds the maximum price limit: 2.4013","requestTime":1734169827285,"data":null}
  Placing 40 open limit order...
  --- Execution finished at 2024-12-14 10:50:36 ---

la paire est définie comme suit :
"LQTY/USDT": {
            "src": "close",
            "ma_base_window": 5,
            "envelopes": [0.07, 0.1, 0.15, 0.2],
            "size": 0.05,
            "sides": ["long", "short"],
        },

Si je comprends bien, l'enveloppe 20% doit dépasser la limite autorisée par bitget.

Ensuite, en executant à nouveau la stratégie, i prend de nouveau une valeur négative (params[position.pair]["canceled_orders_buy"] = 8), provoquant l'arrêt du code.

Je vais tenter en supprimant l'enveloppe 0.2, ou en supprimant completement cette paire.

**Comment by michelflight** [comment]
ah oui, ça c'est bitget, selon les paires on peut pas mettre des ordres limites trop bas ou trop haut, visiblement sur cette paire, bitget oblige des prix min et max très serré

**Comment by P4sc4lS** [comment]
Merci beaucoup de m'avoir mis sur la piste.
Si l'api bitget permet de récupérer les limites de prix, ça pourrait être interressant d'ajouter une condition avant de placer un ordre trigger...Je vais étudier ça

**Comment by michelflight** [comment]
limits = await exchange._session.get_price_limits(pair)
max_price_limit = limits['max']
min_price_limit = limits['min']

if order_price > max_price_limit:
    order_price = max_price_limit
elif order_price < min_price_limit:
    order_price = min_price_limit

**Comment by P4sc4lS** [comment]
super ! Merci 👍

**Comment by michelflight** [comment]
j'ai le même problème que toi, Error limit sell 59 CRV/USDT:USDT - Price 1.19538 - Error => bitget {"code":"22047","msg":"The order price exceeds the maximum price limit: 1.1844","requestTime":1734192063384,"data":null}

**Comment by P4sc4lS** [comment]
De mon coté, pour l'instant j'ai juste supprimé l'enveloppe 0.2 sur la paire concernée, et je n'ai plus d'erreur.
Par contre j'ai constaté que parfois, l'annulation des ordres trigger, avant de placer les nouveaux, ne se fait pas ou seulement partiellement, et je me retrouve avec un nombre d'ordres qui grandit à chaque itération du code.

**Comment by michelflight** [comment]
on dirait qu'il y a quelques sections de codes à revoir, moi j'ai aussi un coup une erreur "no position to close" (même avec hedge_mode=true) un autre coup "maximum price limit" et cette limite je la trouve étrange, ça place sans souci un sl à quasi /2 du prix entry price alors que le tp on ne peut pas avec un prix 2% au dessus. Ayant déjà fait d'autres bots sur bitget j'ai souvent été confronté à des messages d'erreurs qui n'ont rien à voir avec la vraie cause. En attendant de trouver une solution, j'ai mis des paires importantes du top 50 uniquement en me disant que c'est la liquidité des shitcoins qui posent pb, sans certitude.

**Comment by P4sc4lS** [comment]
bonne idée. Je vais suivre ton conseil et supprimer également quelques paires qui pourraient poser problèmes.
Autre phénomène étrange : lorsque je supprime tous les ordres trigger manuellement, la commande `exchange.get_open_trigger_orders(pair) for pair in pairs` me trouve des ordres encore présents alors que la liste est bien vide sur le site bitget.

..., j'ai identifié 5 paires dans ma liste, sur lesquelles les ordres trigger ne sont pas annulés et se cumulent à chaque exécution du code. Ce qui provoque une exposition croissante sur ces paires.
(LQTY/USDT, JASMY/USDT, PEPE/USDT, GMX/USDT, WIF/USDT, ...et surement d'autres non testées)
Pour le moment je les ai supprimées de la liste, en attendant de trouver d'où vient le problème.
